spring.application.name=store-rating

# DATABASE CONFIGURATION
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SpicaLabs}
spring.datasource.username=${DB_USERNAME:taaha}
spring.datasource.password=${DB_PASSWORD:SpicaLabs123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# RENDER PORT
server.port=${PORT:8080}

server.address=0.0.0.0

# DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.web.servlet=DEBUG